#!/bin/bash

DIR_NAME=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "${DIR_NAME}/common.sh"

# get nodes information
source "${DIR_NAME}/gather_nodes"

# get apiservices
source "${DIR_NAME}/gather_apiservices"

# get CRDs
source "${DIR_NAME}/gather_crds"

# get CRs
source "${DIR_NAME}/gather_crs"

# get webhooks
source "${DIR_NAME}/gather_webhooks"

# expand the existing NAMESPACES including kuttl (required for OpenStack CI)
# if exist so we can gather resources about tests
expand_ns "kuttl"

# Trigger Guru Meditation Reports so we then have then in the service logs
source "${DIR_NAME}/gather_trigger_gmr"

# Import functions used in the for loop
source "${DIR_NAME}/gather_services_cm"
source "${DIR_NAME}/gather_secrets"
source "${DIR_NAME}/gather_sub"
source "${DIR_NAME}/gather_ctlplane_resources"

for NS in "${DEFAULT_NAMESPACES[@]}"; do
    # get Services Config (CM)
    gather_services_cm "$NS"
    # get Services Secrets
    gather_secrets "$NS"
    # get subscriptions / installplans / packagemanifests / CSVs
    gather_sub "$NS"
    # get routes, services, jobs, deployments
    # daemonsets, statefulsets, replicasets,
    # pods (describe and get logs)
    gather_ctlplane_resources "$NS"
done

# get network related resources (nncp, ipaddresspool, l2advertisement)
source "${DIR_NAME}/gather_network"

# get SVC status (inspect ctlplane)
source "${DIR_NAME}/gather_services_status"

# get SOS Reports
source "${DIR_NAME}/gather_sos"

# Wait for background tasks to complete
wait_bg
