#!/bin/bash

DIR_NAME=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
# shellcheck disable=SC1091
source "${DIR_NAME}/common.sh"

IFS=$'\n'

# Collect packagemanifests that are global
mkdir -p "${BASE_COLLECTION_PATH}"
/usr/bin/oc get packagemanifest -o yaml >>"${BASE_COLLECTION_PATH}/packagemanifests"

NS="$1"
if [ -z "$NS" ]; then
    echo "No namespace passed, using the default one"
    NS=openstack
fi

# Only get resources if the namespace exists
if ! check_namespace "${NS}"; then
    exit 0
fi

# Get CSVs for the current namespace and collect them in ${BASE_COLLECTION_PATH}/csv
mkdir -p "${BASE_COLLECTION_PATH}/csv/"
for service in $(oc -n "${NS}" get csv -o=custom-columns=NAME:.metadata.name --no-headers)
do
    /usr/bin/oc -n "${NS}" get csv "$service" -o yaml >> "${BASE_COLLECTION_PATH}/csv/$service"
done

mkdir -p "${NAMESPACE_PATH}/${NS}/subscriptions/"
for service in $(oc get subscriptions -n "$NS" -o=custom-columns=NAME:.metadata.name --no-headers)
do
    /usr/bin/oc get subscription "$service" -n "$NS" -o yaml >> "${NAMESPACE_PATH}/${NS}/subscriptions/$service"
done

mkdir -p "${NAMESPACE_PATH}/${NS}/installplans/"
for service in $(oc get installplan -n "$NS" -o=custom-columns=NAME:.metadata.name --no-headers)
do
    /usr/bin/oc get installplan "$service" -n "$NS" -o yaml >> "${NAMESPACE_PATH}/${NS}/installplans/$service"
done

exit 0
