#!/bin/bash

if [[ -z "$DIR_NAME" ]]; then
    CALLED=1
    DIR_NAME=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
    source "${DIR_NAME}/bg.sh"
fi


# Resource list
crds=()

for i in $(/usr/bin/oc get crd | grep openstack.org | awk '{print $1}')
do
  crds+=("$i")
done

echo "Gathering CRDs"
mkdir -p "$BASE_COLLECTION_PATH"/crd

# Run the collection of resources using must-gather
for resource in "${crds[@]}"; do
  run_bg /usr/bin/oc get crd "$resource" -o yaml > "${BASE_COLLECTION_PATH}/crd/${resource}.yaml"
done

[[ $CALLED -eq 1 ]] && wait_bg
