#!/bin/bash

if [[ -z "$DIR_NAME" ]]; then
    CALLED=1
    DIR_NAME=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
    source "${DIR_NAME}/common.sh"
fi

# Resource list
resources=()

# explicitly adding rabbitmq in the grep because we rely on the rabbitmq-cluster-operator
for i in $(/usr/bin/oc get apiservices --all-namespaces | grep -E "(openstack|rabbitmq)\.(org|com)" | awk '{ print $1 }')
do
  resources+=("$i")
done

for resource in "${resources[@]}"; do
  mkdir -p "$BASE_COLLECTION_PATH"/apiservices/
  run_bg /usr/bin/oc get apiservice "${resource}" -o yaml '>' "${BASE_COLLECTION_PATH}/apiservices/${resource}.yaml"
done

[[ $CALLED -eq 1 ]] && wait_bg
