#!/bin/bash

# load shared functions and data when not sourced
if [[ -z "$DIR_NAME" ]]; then
    CALLED=1
    DIR_NAME=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
    source "${DIR_NAME}/common.sh"
fi


function get_things {
    local NS=$1
    local object=$2
    local dest=$3
    mkdir -p "$dest"

    echo "Gathering $object"
    IFS=$'\n'
    for service in $(oc -n "${NS}" get $object -o=custom-columns=NAME:.metadata.name --no-headers); do
        run_bg /usr/bin/oc get $object "$service" -n "${NS}" -o yaml '>>' "${dest}/$service"
    done
    unset IFS
}


function gather_sub {
    local NS="$1"

    # Collect packagemanifests that are global
    mkdir -p "${BASE_COLLECTION_PATH}"
    run_bg /usr/bin/oc get packagemanifest -o yaml '>>' "${BASE_COLLECTION_PATH}/packagemanifests"

    # Only get resources if the namespace exists
    if ! check_namespace "${NS}"; then
        return
    fi

    # Get CSVs for the current namespace and collect them in ${BASE_COLLECTION_PATH}/csv
    get_things "$NS" csv "${BASE_COLLECTION_PATH}/csv/"
    get_things "$NS" subscription "${NAMESPACE_PATH}/${NS}/subscriptions/"
    get_things "$NS" installplan "${NAMESPACE_PATH}/${NS}/installplans/"
}


if [[ $CALLED -eq 1 ]]; then
    NS="$1"
    if [ -z "$NS" ]; then
        echo "No namespace passed, using the default one"
        NS=openstack
    fi

    gather_sub "$NS"

    wait_bg
fi
