#!/bin/bash

# load shared functions and data
DIR_NAME=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
# shellcheck disable=SC1091
source "${DIR_NAME}/common.sh"

NS="$1"
if [ -z "$NS" ]; then
    echo "No namespace passed, using the default one"
    NS=openstack
fi

# Only get resources if the namespace exists
if ! check_namespace "${NS}"; then
    exit 0
fi

# TODO: Get secrets where a must-gather label is set. The following command
# get everything at the moment. All the retrieved yaml file present the .data
# section with a base64 encoded value, which represents the whole content of
# the secret.
function get_secrets {
    local service=$1
    for s in $(/usr/bin/oc -n "$NS" get secrets | grep -vE "(token|dockercfg)" | awk -v s="$service" '$0 ~ s {print $1}'); do
        mkdir -p "$NAMESPACE_PATH"/"$NS"/secrets/"$service"
        /usr/bin/oc -n "$NS" get secret "$s" -o yaml > "$NAMESPACE_PATH"/"$NS"/secrets/"$service"/"$s".yaml;
    done
}

for service in "${OSP_SERVICES[@]}"; do
   get_secrets "$service"
done
# All secrets have been collected, apply masking on the entire directory
/usr/bin/mask.py --dir "$NAMESPACE_PATH"/"$NS"/secrets
