#!/bin/bash
#
# This is the main script that is invoked when we call `oc adm must-gather`,
# and it is called directly regardless of the ENTRYPOINT in the Dockerfile
#
# This file is necessary to pipe the output of the must-gather process to the
# output directory.

LOG_DIR="${BASE_COLLECTION_PATH:-/must-gather}"
LOG="${LOG_DIR}/run.log"

/usr/bin/gather_run 2>&1 | tee "${LOG}"

# Ensure all files are flushed to disk before we finish and copying begins
sync
