#!/bin/bash

if [[ -z "$DIR_NAME" ]]; then
    CALLED=1
    DIR_NAME=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
    source "${DIR_NAME}/bg.sh"
fi

echo "Writing validating webhooks"
mkdir -p "${WEBHOOKS_COLLECTION_PATH}/validating"
for resource in $(/usr/bin/oc get validatingwebhookconfiguration -o custom-columns=NAME:.metadata.name --no-headers); do
  run_bg /usr/bin/oc get validatingwebhookconfiguration "${resource}" -o yaml '>' "${WEBHOOKS_COLLECTION_PATH}/validating/${resource}.yaml"
done

echo "Writing mutating webhooks"
mkdir -p "${WEBHOOKS_COLLECTION_PATH}/mutating"
for resource in $(/usr/bin/oc get mutatingwebhookconfiguration -o custom-columns=NAME:.metadata.name --no-headers); do
  run_bg /usr/bin/oc get mutatingwebhookconfiguration "${resource}" -o yaml '|' grep -vi cabundle '>' "${WEBHOOKS_COLLECTION_PATH}/mutating/${resource}.yaml"
done

[[ $CALLED -eq 1 ]] && wait_bg
