#!/bin/bash

mkdir -p "${NODES_COLLECTION_PATH}"
for node in $(/usr/bin/oc get nodes -o custom-columns=NAME:.metadata.name --no-headers); do
    /usr/bin/oc get nodes "${node}" -o yaml > "${NODES_COLLECTION_PATH}/${node}.yaml"
done

exit 0
