#!/bin/bash

if [[ -z "$DIR_NAME" ]]; then
    CALLED=1
    DIR_NAME=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
    source "${DIR_NAME}/common.sh"
fi

# Resource list
apiservices=()

# explicitly adding rabbitmq in the grep because the rabbitmq-cluster-operator may be present
for i in $(/usr/bin/oc get apiservices --all-namespaces | awk '/(openstack|rabbitmq)\.(org|com)/ { print $1 }'); do
    apiservices+=("$i")
done

for resource in "${apiservices[@]}"; do
  mkdir -p "$BASE_COLLECTION_PATH"/apiservices/
  run_bg /usr/bin/oc get apiservice "${resource}" -o yaml '>' "${BASE_COLLECTION_PATH}/apiservices/${resource}.yaml"
done

[[ $CALLED -eq 1 ]] && wait_bg
