name: Sanity Check

on: [push, pull_request]

jobs:
  make_check:
    name: check for issues in the collection_scripts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Setup python
        uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c # v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: sudo apt-get install -y make
      - name: Install tox and any other packages
        run: pip install tox
      - name: Run ShellCheck
        run: make check
      - name: Run PyTest
        run: make pytest
